// Code generated by ogen, DO NOT EDIT.

package marzban

// setDefaults set default value of fields.
func (s *BodyAdminTokenAPIAdminTokenPost) setDefaults() {
	{
		val := string("")
		s.Scope.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Conflict) setDefaults() {
	{
		val := string("Entity already exists")
		s.Detail.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Forbidden) setDefaults() {
	{
		val := string("You are not allowed to ...")
		s.Detail.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NextPlanModel) setDefaults() {
	{
		val := bool(false)
		s.AddRemainingTraffic.SetTo(val)
	}
	{
		val := bool(true)
		s.FireOnEither.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NodeCreate) setDefaults() {
	{
		val := int(62050)
		s.Port.SetTo(val)
	}
	{
		val := int(62051)
		s.APIPort.SetTo(val)
	}
	{
		val := float64(1)
		s.UsageCoefficient.SetTo(val)
	}
	{
		val := bool(true)
		s.AddAsNewHost.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NodeResponse) setDefaults() {
	{
		val := int(62050)
		s.Port.SetTo(val)
	}
	{
		val := int(62051)
		s.APIPort.SetTo(val)
	}
	{
		val := float64(1)
		s.UsageCoefficient.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NodeSettings) setDefaults() {
	{
		val := string("v0.2.0")
		s.MinNodeVersion.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NotFound) setDefaults() {
	{
		val := string("Entity {} not found")
		s.Detail.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ProxyHost) setDefaults() {
	{
		val := ProxyHostSecurity("inbound_default")
		s.Security.SetTo(val)
	}
	{
		val := ProxyHostALPN("")
		s.Alpn.SetTo(val)
	}
	{
		val := ProxyHostFingerprint("")
		s.Fingerprint.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubscriptionUserResponse) setDefaults() {
	{
		val := UserDataLimitResetStrategy("no_reset")
		s.DataLimitResetStrategy.SetTo(val)
	}
	{
		val := int(0)
		s.LifetimeUsedTraffic.SetTo(val)
	}
	{
		val := string("")
		s.SubscriptionURL.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Token) setDefaults() {
	{
		val := string("bearer")
		s.TokenType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Unauthorized) setDefaults() {
	{
		val := string("Not authenticated")
		s.Detail.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserCreate) setDefaults() {
	{
		val := UserDataLimitResetStrategy("no_reset")
		s.DataLimitResetStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserModify) setDefaults() {
	{
		val := UserDataLimitResetStrategy("no_reset")
		s.DataLimitResetStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserResponse) setDefaults() {
	{
		val := UserDataLimitResetStrategy("no_reset")
		s.DataLimitResetStrategy.SetTo(val)
	}
	{
		val := int(0)
		s.LifetimeUsedTraffic.SetTo(val)
	}
	{
		val := string("")
		s.SubscriptionURL.SetTo(val)
	}
}
