// Code generated by ogen, DO NOT EDIT.

package marzban

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ActivateAllDisabledUsers implements activate_all_disabled_users operation.
	//
	// Activate all disabled users under a specific admin.
	//
	// POST /api/admin/{username}/users/activate
	ActivateAllDisabledUsers(ctx context.Context, params ActivateAllDisabledUsersParams) (ActivateAllDisabledUsersRes, error)
	// ActiveNextPlan implements active_next_plan operation.
	//
	// Reset user by next plan.
	//
	// POST /api/user/{username}/active-next
	ActiveNextPlan(ctx context.Context, params ActiveNextPlanParams) (ActiveNextPlanRes, error)
	// AddNode implements add_node operation.
	//
	// Add a new node to the database and optionally add it as a host.
	//
	// POST /api/node
	AddNode(ctx context.Context, req *NodeCreate) (AddNodeRes, error)
	// AddUser implements add_user operation.
	//
	// Add a new user
	// - **username**: 3 to 32 characters, can include a-z, 0-9, and underscores.
	// - **status**: User's status, defaults to `active`. Special rules if `on_hold`.
	// - **expire**: UTC timestamp for account expiration. Use `0` for unlimited.
	// - **data_limit**: Max data usage in bytes (e.g., `1073741824` for 1GB). `0` means unlimited.
	// - **data_limit_reset_strategy**: Defines how/if data limit resets. `no_reset` means it never
	// resets.
	// - **proxies**: Dictionary of protocol settings (e.g., `vmess`, `vless`).
	// - **inbounds**: Dictionary of protocol tags to specify inbound connections.
	// - **note**: Optional text field for additional user information or notes.
	// - **on_hold_timeout**: UTC timestamp when `on_hold` status should start or end.
	// - **on_hold_expire_duration**: Duration (in seconds) for how long the user should stay in
	// `on_hold` status.
	// - **next_plan**: Next user plan (resets after use).
	//
	// POST /api/user
	AddUser(ctx context.Context, req *UserCreate) (AddUserRes, error)
	// AddUserTemplate implements add_user_template operation.
	//
	// Add a new user template
	// - **name** can be up to 64 characters
	// - **data_limit** must be in bytes and larger or equal to 0
	// - **expire_duration** must be in seconds and larger or equat to 0
	// - **inbounds** dictionary of protocol:inbound_tags, empty means all inbounds.
	//
	// POST /api/user_template
	AddUserTemplate(ctx context.Context, req *UserTemplateCreate) (AddUserTemplateRes, error)
	// AdminToken implements admin_token operation.
	//
	// Authenticate an admin and issue a token.
	//
	// POST /api/admin/token
	AdminToken(ctx context.Context, req *BodyAdminTokenAPIAdminTokenPost) (AdminTokenRes, error)
	// Base implements base operation.
	//
	// Base.
	//
	// GET /
	Base(ctx context.Context) (BaseOK, error)
	// CreateAdmin implements create_admin operation.
	//
	// Create a new admin if the current admin has sudo privileges.
	//
	// POST /api/admin
	CreateAdmin(ctx context.Context, req *AdminCreate) (CreateAdminRes, error)
	// DeleteExpiredUsers implements delete_expired_users operation.
	//
	// Delete users who have expired within the specified date range.
	// - **expired_after** UTC datetime (optional)
	// - **expired_before** UTC datetime (optional)
	// - At least one of expired_after or expired_before must be provided.
	//
	// DELETE /api/users/expired
	DeleteExpiredUsers(ctx context.Context, params DeleteExpiredUsersParams) (DeleteExpiredUsersRes, error)
	// DisableAllActiveUsers implements disable_all_active_users operation.
	//
	// Disable all active users under a specific admin.
	//
	// POST /api/admin/{username}/users/disable
	DisableAllActiveUsers(ctx context.Context, params DisableAllActiveUsersParams) (DisableAllActiveUsersRes, error)
	// GetAdminUsage implements get_admin_usage operation.
	//
	// Retrieve the usage of given admin.
	//
	// GET /api/admin/usage/{username}
	GetAdminUsage(ctx context.Context, params GetAdminUsageParams) (GetAdminUsageRes, error)
	// GetAdmins implements get_admins operation.
	//
	// Fetch a list of admins with optional filters for pagination and username.
	//
	// GET /api/admins
	GetAdmins(ctx context.Context, params GetAdminsParams) (GetAdminsRes, error)
	// GetCoreConfig implements get_core_config operation.
	//
	// Get the current core configuration.
	//
	// GET /api/core/config
	GetCoreConfig(ctx context.Context) (GetCoreConfigRes, error)
	// GetCoreStats implements get_core_stats operation.
	//
	// Retrieve core statistics such as version and uptime.
	//
	// GET /api/core
	GetCoreStats(ctx context.Context) (GetCoreStatsRes, error)
	// GetCurrentAdmin implements get_current_admin operation.
	//
	// Retrieve the current authenticated admin.
	//
	// GET /api/admin
	GetCurrentAdmin(ctx context.Context) (GetCurrentAdminRes, error)
	// GetExpiredUsers implements get_expired_users operation.
	//
	// Get users who have expired within the specified date range.
	// - **expired_after** UTC datetime (optional)
	// - **expired_before** UTC datetime (optional)
	// - At least one of expired_after or expired_before must be provided for filtering
	// - If both are omitted, returns all expired users.
	//
	// GET /api/users/expired
	GetExpiredUsers(ctx context.Context, params GetExpiredUsersParams) (GetExpiredUsersRes, error)
	// GetHosts implements get_hosts operation.
	//
	// Get a list of proxy hosts grouped by inbound tag.
	//
	// GET /api/hosts
	GetHosts(ctx context.Context) (GetHostsRes, error)
	// GetInbounds implements get_inbounds operation.
	//
	// Retrieve inbound configurations grouped by protocol.
	//
	// GET /api/inbounds
	GetInbounds(ctx context.Context) (GetInboundsRes, error)
	// GetNode implements get_node operation.
	//
	// Retrieve details of a specific node by its ID.
	//
	// GET /api/node/{node_id}
	GetNode(ctx context.Context, params GetNodeParams) (GetNodeRes, error)
	// GetNodeSettings implements get_node_settings operation.
	//
	// Retrieve the current node settings, including TLS certificate.
	//
	// GET /api/node/settings
	GetNodeSettings(ctx context.Context) (GetNodeSettingsRes, error)
	// GetNodes implements get_nodes operation.
	//
	// Retrieve a list of all nodes. Accessible only to sudo admins.
	//
	// GET /api/nodes
	GetNodes(ctx context.Context) (GetNodesRes, error)
	// GetSystemStats implements get_system_stats operation.
	//
	// Fetch system stats including memory, CPU, and user metrics.
	//
	// GET /api/system
	GetSystemStats(ctx context.Context) (GetSystemStatsRes, error)
	// GetUsage implements get_usage operation.
	//
	// Retrieve usage statistics for nodes within a specified date range.
	//
	// GET /api/nodes/usage
	GetUsage(ctx context.Context, params GetUsageParams) (GetUsageRes, error)
	// GetUser implements get_user operation.
	//
	// Get user information.
	//
	// GET /api/user/{username}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// GetUserTemplateEndpoint implements get_user_template_endpoint operation.
	//
	// Get User Template information with id.
	//
	// GET /api/user_template/{template_id}
	GetUserTemplateEndpoint(ctx context.Context, params GetUserTemplateEndpointParams) (GetUserTemplateEndpointRes, error)
	// GetUserTemplates implements get_user_templates operation.
	//
	// Get a list of User Templates with optional pagination.
	//
	// GET /api/user_template
	GetUserTemplates(ctx context.Context, params GetUserTemplatesParams) (GetUserTemplatesRes, error)
	// GetUserUsage implements get_user_usage operation.
	//
	// Get users usage.
	//
	// GET /api/user/{username}/usage
	GetUserUsage(ctx context.Context, params GetUserUsageParams) (GetUserUsageRes, error)
	// GetUsers implements get_users operation.
	//
	// Get all users.
	//
	// GET /api/users
	GetUsers(ctx context.Context, params GetUsersParams) (GetUsersRes, error)
	// GetUsersUsage implements get_users_usage operation.
	//
	// Get all users usage.
	//
	// GET /api/users/usage
	GetUsersUsage(ctx context.Context, params GetUsersUsageParams) (GetUsersUsageRes, error)
	// ModifyAdmin implements modify_admin operation.
	//
	// Modify an existing admin's details.
	//
	// PUT /api/admin/{username}
	ModifyAdmin(ctx context.Context, req *AdminModify, params ModifyAdminParams) (ModifyAdminRes, error)
	// ModifyCoreConfig implements modify_core_config operation.
	//
	// Modify the core configuration and restart the core.
	//
	// PUT /api/core/config
	ModifyCoreConfig(ctx context.Context, req *ModifyCoreConfigReq) (ModifyCoreConfigRes, error)
	// ModifyHosts implements modify_hosts operation.
	//
	// Modify proxy hosts and update the configuration.
	//
	// PUT /api/hosts
	ModifyHosts(ctx context.Context, req ModifyHostsReq) (ModifyHostsRes, error)
	// ModifyNode implements modify_node operation.
	//
	// Update a node's details. Only accessible to sudo admins.
	//
	// PUT /api/node/{node_id}
	ModifyNode(ctx context.Context, req *NodeModify, params ModifyNodeParams) (ModifyNodeRes, error)
	// ModifyUser implements modify_user operation.
	//
	// Modify an existing user
	// - **username**: Cannot be changed. Used to identify the user.
	// - **status**: User's new status. Can be 'active', 'disabled', 'on_hold', 'limited', or 'expired'.
	// - **expire**: UTC timestamp for new account expiration. Set to `0` for unlimited, `null` for no
	// change.
	// - **data_limit**: New max data usage in bytes (e.g., `1073741824` for 1GB). Set to `0` for
	// unlimited, `null` for no change.
	// - **data_limit_reset_strategy**: New strategy for data limit reset. Options include 'daily',
	// 'weekly', 'monthly', or 'no_reset'.
	// - **proxies**: Dictionary of new protocol settings (e.g., `vmess`, `vless`). Empty dictionary
	// means no change.
	// - **inbounds**: Dictionary of new protocol tags to specify inbound connections. Empty dictionary
	// means no change.
	// - **note**: New optional text for additional user information or notes. `null` means no change.
	// - **on_hold_timeout**: New UTC timestamp for when `on_hold` status should start or end. Only
	// applicable if status is changed to 'on_hold'.
	// - **on_hold_expire_duration**: New duration (in seconds) for how long the user should stay in
	// `on_hold` status. Only applicable if status is changed to 'on_hold'.
	// - **next_plan**: Next user plan (resets after use).
	// Note: Fields set to `null` or omitted will not be modified.
	//
	// PUT /api/user/{username}
	ModifyUser(ctx context.Context, req *UserModify, params ModifyUserParams) (ModifyUserRes, error)
	// ModifyUserTemplate implements modify_user_template operation.
	//
	// Modify User Template
	// - **name** can be up to 64 characters
	// - **data_limit** must be in bytes and larger or equal to 0
	// - **expire_duration** must be in seconds and larger or equat to 0
	// - **inbounds** dictionary of protocol:inbound_tags, empty means all inbounds.
	//
	// PUT /api/user_template/{template_id}
	ModifyUserTemplate(ctx context.Context, req *UserTemplateModify, params ModifyUserTemplateParams) (ModifyUserTemplateRes, error)
	// ReconnectNode implements reconnect_node operation.
	//
	// Trigger a reconnection for the specified node. Only accessible to sudo admins.
	//
	// POST /api/node/{node_id}/reconnect
	ReconnectNode(ctx context.Context, params ReconnectNodeParams) (ReconnectNodeRes, error)
	// RemoveAdmin implements remove_admin operation.
	//
	// Remove an admin from the database.
	//
	// DELETE /api/admin/{username}
	RemoveAdmin(ctx context.Context, params RemoveAdminParams) (RemoveAdminRes, error)
	// RemoveNode implements remove_node operation.
	//
	// Delete a node and remove it from xray in the background.
	//
	// DELETE /api/node/{node_id}
	RemoveNode(ctx context.Context, params RemoveNodeParams) (RemoveNodeRes, error)
	// RemoveUser implements remove_user operation.
	//
	// Remove a user.
	//
	// DELETE /api/user/{username}
	RemoveUser(ctx context.Context, params RemoveUserParams) (RemoveUserRes, error)
	// RemoveUserTemplate implements remove_user_template operation.
	//
	// Remove a User Template by its ID.
	//
	// DELETE /api/user_template/{template_id}
	RemoveUserTemplate(ctx context.Context, params RemoveUserTemplateParams) (RemoveUserTemplateRes, error)
	// ResetAdminUsage implements reset_admin_usage operation.
	//
	// Resets usage of admin.
	//
	// POST /api/admin/usage/reset/{username}
	ResetAdminUsage(ctx context.Context, params ResetAdminUsageParams) (ResetAdminUsageRes, error)
	// ResetUserDataUsage implements reset_user_data_usage operation.
	//
	// Reset user data usage.
	//
	// POST /api/user/{username}/reset
	ResetUserDataUsage(ctx context.Context, params ResetUserDataUsageParams) (ResetUserDataUsageRes, error)
	// ResetUsersDataUsage implements reset_users_data_usage operation.
	//
	// Reset all users data usage.
	//
	// POST /api/users/reset
	ResetUsersDataUsage(ctx context.Context) (ResetUsersDataUsageRes, error)
	// RestartCore implements restart_core operation.
	//
	// Restart the core and all connected nodes.
	//
	// POST /api/core/restart
	RestartCore(ctx context.Context) (RestartCoreRes, error)
	// RevokeUserSubscription implements revoke_user_subscription operation.
	//
	// Revoke users subscription (Subscription link and proxies).
	//
	// POST /api/user/{username}/revoke_sub
	RevokeUserSubscription(ctx context.Context, params RevokeUserSubscriptionParams) (RevokeUserSubscriptionRes, error)
	// SetOwner implements set_owner operation.
	//
	// Set a new owner (admin) for a user.
	//
	// PUT /api/user/{username}/set-owner
	SetOwner(ctx context.Context, params SetOwnerParams) (SetOwnerRes, error)
	// UserGetUsage implements user_get_usage operation.
	//
	// Fetches the usage statistics for the user within a specified date range.
	//
	// GET /sub/{token}/usage
	UserGetUsage(ctx context.Context, params UserGetUsageParams) (UserGetUsageRes, error)
	// UserSubscription implements user_subscription operation.
	//
	// Provides a subscription link based on the user agent (Clash, V2Ray, etc.).
	//
	// GET /sub/{token}/
	UserSubscription(ctx context.Context, params UserSubscriptionParams) (UserSubscriptionRes, error)
	// UserSubscriptionInfo implements user_subscription_info operation.
	//
	// Retrieves detailed information about the user's subscription.
	//
	// GET /sub/{token}/info
	UserSubscriptionInfo(ctx context.Context, params UserSubscriptionInfoParams) (UserSubscriptionInfoRes, error)
	// UserSubscriptionWithClientType implements user_subscription_with_client_type operation.
	//
	// Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).
	//
	// GET /sub/{token}/{client_type}
	UserSubscriptionWithClientType(ctx context.Context, params UserSubscriptionWithClientTypeParams) (UserSubscriptionWithClientTypeRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
