// Code generated by ogen, DO NOT EDIT.
package marzban

type ActivateAllDisabledUsersRes interface {
	activateAllDisabledUsersRes()
}

type ActiveNextPlanRes interface {
	activeNextPlanRes()
}

type AddNodeRes interface {
	addNodeRes()
}

type AddUserRes interface {
	addUserRes()
}

type AddUserTemplateRes interface {
	addUserTemplateRes()
}

type AdminTokenRes interface {
	adminTokenRes()
}

type CreateAdminRes interface {
	createAdminRes()
}

type DeleteExpiredUsersRes interface {
	deleteExpiredUsersRes()
}

type DisableAllActiveUsersRes interface {
	disableAllActiveUsersRes()
}

type GetAdminUsageRes interface {
	getAdminUsageRes()
}

type GetAdminsRes interface {
	getAdminsRes()
}

type GetCoreConfigRes interface {
	getCoreConfigRes()
}

type GetCoreStatsRes interface {
	getCoreStatsRes()
}

type GetCurrentAdminRes interface {
	getCurrentAdminRes()
}

type GetExpiredUsersRes interface {
	getExpiredUsersRes()
}

type GetHostsRes interface {
	getHostsRes()
}

type GetInboundsRes interface {
	getInboundsRes()
}

type GetNodeRes interface {
	getNodeRes()
}

type GetNodeSettingsRes interface {
	getNodeSettingsRes()
}

type GetNodesRes interface {
	getNodesRes()
}

type GetSystemStatsRes interface {
	getSystemStatsRes()
}

type GetUsageRes interface {
	getUsageRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUserTemplateEndpointRes interface {
	getUserTemplateEndpointRes()
}

type GetUserTemplatesRes interface {
	getUserTemplatesRes()
}

type GetUserUsageRes interface {
	getUserUsageRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type GetUsersUsageRes interface {
	getUsersUsageRes()
}

type ModifyAdminRes interface {
	modifyAdminRes()
}

type ModifyCoreConfigRes interface {
	modifyCoreConfigRes()
}

type ModifyHostsRes interface {
	modifyHostsRes()
}

type ModifyNodeRes interface {
	modifyNodeRes()
}

type ModifyUserRes interface {
	modifyUserRes()
}

type ModifyUserTemplateRes interface {
	modifyUserTemplateRes()
}

type ReconnectNodeRes interface {
	reconnectNodeRes()
}

type RemoveAdminRes interface {
	removeAdminRes()
}

type RemoveNodeRes interface {
	removeNodeRes()
}

type RemoveUserRes interface {
	removeUserRes()
}

type RemoveUserTemplateRes interface {
	removeUserTemplateRes()
}

type ResetAdminUsageRes interface {
	resetAdminUsageRes()
}

type ResetUserDataUsageRes interface {
	resetUserDataUsageRes()
}

type ResetUsersDataUsageRes interface {
	resetUsersDataUsageRes()
}

type RestartCoreRes interface {
	restartCoreRes()
}

type RevokeUserSubscriptionRes interface {
	revokeUserSubscriptionRes()
}

type SetOwnerRes interface {
	setOwnerRes()
}

type UserGetUsageRes interface {
	userGetUsageRes()
}

type UserSubscriptionInfoRes interface {
	userSubscriptionInfoRes()
}

type UserSubscriptionRes interface {
	userSubscriptionRes()
}

type UserSubscriptionWithClientTypeRes interface {
	userSubscriptionWithClientTypeRes()
}
