// Code generated by ogen, DO NOT EDIT.

package marzban

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleOAuth2PasswordBearer handles OAuth2PasswordBearer security.
	HandleOAuth2PasswordBearer(ctx context.Context, operationName OperationName, t OAuth2PasswordBearer) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var oauth2ScopesOAuth2PasswordBearer = map[string][]string{
	ActivateAllDisabledUsersOperation: []string{},
	ActiveNextPlanOperation:           []string{},
	AddNodeOperation:                  []string{},
	AddUserOperation:                  []string{},
	AddUserTemplateOperation:          []string{},
	CreateAdminOperation:              []string{},
	DeleteExpiredUsersOperation:       []string{},
	DisableAllActiveUsersOperation:    []string{},
	GetAdminUsageOperation:            []string{},
	GetAdminsOperation:                []string{},
	GetCoreConfigOperation:            []string{},
	GetCoreStatsOperation:             []string{},
	GetCurrentAdminOperation:          []string{},
	GetExpiredUsersOperation:          []string{},
	GetHostsOperation:                 []string{},
	GetInboundsOperation:              []string{},
	GetNodeOperation:                  []string{},
	GetNodeSettingsOperation:          []string{},
	GetNodesOperation:                 []string{},
	GetSystemStatsOperation:           []string{},
	GetUsageOperation:                 []string{},
	GetUserOperation:                  []string{},
	GetUserTemplateEndpointOperation:  []string{},
	GetUserTemplatesOperation:         []string{},
	GetUserUsageOperation:             []string{},
	GetUsersOperation:                 []string{},
	GetUsersUsageOperation:            []string{},
	ModifyAdminOperation:              []string{},
	ModifyCoreConfigOperation:         []string{},
	ModifyHostsOperation:              []string{},
	ModifyNodeOperation:               []string{},
	ModifyUserOperation:               []string{},
	ModifyUserTemplateOperation:       []string{},
	ReconnectNodeOperation:            []string{},
	RemoveAdminOperation:              []string{},
	RemoveNodeOperation:               []string{},
	RemoveUserOperation:               []string{},
	RemoveUserTemplateOperation:       []string{},
	ResetAdminUsageOperation:          []string{},
	ResetUserDataUsageOperation:       []string{},
	ResetUsersDataUsageOperation:      []string{},
	RestartCoreOperation:              []string{},
	RevokeUserSubscriptionOperation:   []string{},
	SetOwnerOperation:                 []string{},
}

func (s *Server) securityOAuth2PasswordBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t OAuth2PasswordBearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Scopes = oauth2ScopesOAuth2PasswordBearer[operationName]
	rctx, err := s.sec.HandleOAuth2PasswordBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// OAuth2PasswordBearer provides OAuth2PasswordBearer security value.
	OAuth2PasswordBearer(ctx context.Context, operationName OperationName) (OAuth2PasswordBearer, error)
}

func (s *Client) securityOAuth2PasswordBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth2PasswordBearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth2PasswordBearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
