// Code generated by ogen, DO NOT EDIT.

package marzban

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActivateAllDisabledUsers implements activate_all_disabled_users operation.
//
// Activate all disabled users under a specific admin.
//
// POST /api/admin/{username}/users/activate
func (UnimplementedHandler) ActivateAllDisabledUsers(ctx context.Context, params ActivateAllDisabledUsersParams) (r ActivateAllDisabledUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActiveNextPlan implements active_next_plan operation.
//
// Reset user by next plan.
//
// POST /api/user/{username}/active-next
func (UnimplementedHandler) ActiveNextPlan(ctx context.Context, params ActiveNextPlanParams) (r ActiveNextPlanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddNode implements add_node operation.
//
// Add a new node to the database and optionally add it as a host.
//
// POST /api/node
func (UnimplementedHandler) AddNode(ctx context.Context, req *NodeCreate) (r AddNodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddUser implements add_user operation.
//
// Add a new user
// - **username**: 3 to 32 characters, can include a-z, 0-9, and underscores.
// - **status**: User's status, defaults to `active`. Special rules if `on_hold`.
// - **expire**: UTC timestamp for account expiration. Use `0` for unlimited.
// - **data_limit**: Max data usage in bytes (e.g., `1073741824` for 1GB). `0` means unlimited.
// - **data_limit_reset_strategy**: Defines how/if data limit resets. `no_reset` means it never
// resets.
// - **proxies**: Dictionary of protocol settings (e.g., `vmess`, `vless`).
// - **inbounds**: Dictionary of protocol tags to specify inbound connections.
// - **note**: Optional text field for additional user information or notes.
// - **on_hold_timeout**: UTC timestamp when `on_hold` status should start or end.
// - **on_hold_expire_duration**: Duration (in seconds) for how long the user should stay in
// `on_hold` status.
// - **next_plan**: Next user plan (resets after use).
//
// POST /api/user
func (UnimplementedHandler) AddUser(ctx context.Context, req *UserCreate) (r AddUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddUserTemplate implements add_user_template operation.
//
// Add a new user template
// - **name** can be up to 64 characters
// - **data_limit** must be in bytes and larger or equal to 0
// - **expire_duration** must be in seconds and larger or equat to 0
// - **inbounds** dictionary of protocol:inbound_tags, empty means all inbounds.
//
// POST /api/user_template
func (UnimplementedHandler) AddUserTemplate(ctx context.Context, req *UserTemplateCreate) (r AddUserTemplateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminToken implements admin_token operation.
//
// Authenticate an admin and issue a token.
//
// POST /api/admin/token
func (UnimplementedHandler) AdminToken(ctx context.Context, req *BodyAdminTokenAPIAdminTokenPost) (r AdminTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Base implements base operation.
//
// Base.
//
// GET /
func (UnimplementedHandler) Base(ctx context.Context) (r BaseOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdmin implements create_admin operation.
//
// Create a new admin if the current admin has sudo privileges.
//
// POST /api/admin
func (UnimplementedHandler) CreateAdmin(ctx context.Context, req *AdminCreate) (r CreateAdminRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteExpiredUsers implements delete_expired_users operation.
//
// Delete users who have expired within the specified date range.
// - **expired_after** UTC datetime (optional)
// - **expired_before** UTC datetime (optional)
// - At least one of expired_after or expired_before must be provided.
//
// DELETE /api/users/expired
func (UnimplementedHandler) DeleteExpiredUsers(ctx context.Context, params DeleteExpiredUsersParams) (r DeleteExpiredUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DisableAllActiveUsers implements disable_all_active_users operation.
//
// Disable all active users under a specific admin.
//
// POST /api/admin/{username}/users/disable
func (UnimplementedHandler) DisableAllActiveUsers(ctx context.Context, params DisableAllActiveUsersParams) (r DisableAllActiveUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdminUsage implements get_admin_usage operation.
//
// Retrieve the usage of given admin.
//
// GET /api/admin/usage/{username}
func (UnimplementedHandler) GetAdminUsage(ctx context.Context, params GetAdminUsageParams) (r GetAdminUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdmins implements get_admins operation.
//
// Fetch a list of admins with optional filters for pagination and username.
//
// GET /api/admins
func (UnimplementedHandler) GetAdmins(ctx context.Context, params GetAdminsParams) (r GetAdminsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCoreConfig implements get_core_config operation.
//
// Get the current core configuration.
//
// GET /api/core/config
func (UnimplementedHandler) GetCoreConfig(ctx context.Context) (r GetCoreConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCoreStats implements get_core_stats operation.
//
// Retrieve core statistics such as version and uptime.
//
// GET /api/core
func (UnimplementedHandler) GetCoreStats(ctx context.Context) (r GetCoreStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentAdmin implements get_current_admin operation.
//
// Retrieve the current authenticated admin.
//
// GET /api/admin
func (UnimplementedHandler) GetCurrentAdmin(ctx context.Context) (r GetCurrentAdminRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExpiredUsers implements get_expired_users operation.
//
// Get users who have expired within the specified date range.
// - **expired_after** UTC datetime (optional)
// - **expired_before** UTC datetime (optional)
// - At least one of expired_after or expired_before must be provided for filtering
// - If both are omitted, returns all expired users.
//
// GET /api/users/expired
func (UnimplementedHandler) GetExpiredUsers(ctx context.Context, params GetExpiredUsersParams) (r GetExpiredUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHosts implements get_hosts operation.
//
// Get a list of proxy hosts grouped by inbound tag.
//
// GET /api/hosts
func (UnimplementedHandler) GetHosts(ctx context.Context) (r GetHostsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInbounds implements get_inbounds operation.
//
// Retrieve inbound configurations grouped by protocol.
//
// GET /api/inbounds
func (UnimplementedHandler) GetInbounds(ctx context.Context) (r GetInboundsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNode implements get_node operation.
//
// Retrieve details of a specific node by its ID.
//
// GET /api/node/{node_id}
func (UnimplementedHandler) GetNode(ctx context.Context, params GetNodeParams) (r GetNodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNodeSettings implements get_node_settings operation.
//
// Retrieve the current node settings, including TLS certificate.
//
// GET /api/node/settings
func (UnimplementedHandler) GetNodeSettings(ctx context.Context) (r GetNodeSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNodes implements get_nodes operation.
//
// Retrieve a list of all nodes. Accessible only to sudo admins.
//
// GET /api/nodes
func (UnimplementedHandler) GetNodes(ctx context.Context) (r GetNodesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSystemStats implements get_system_stats operation.
//
// Fetch system stats including memory, CPU, and user metrics.
//
// GET /api/system
func (UnimplementedHandler) GetSystemStats(ctx context.Context) (r GetSystemStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsage implements get_usage operation.
//
// Retrieve usage statistics for nodes within a specified date range.
//
// GET /api/nodes/usage
func (UnimplementedHandler) GetUsage(ctx context.Context, params GetUsageParams) (r GetUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements get_user operation.
//
// Get user information.
//
// GET /api/user/{username}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserTemplateEndpoint implements get_user_template_endpoint operation.
//
// Get User Template information with id.
//
// GET /api/user_template/{template_id}
func (UnimplementedHandler) GetUserTemplateEndpoint(ctx context.Context, params GetUserTemplateEndpointParams) (r GetUserTemplateEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserTemplates implements get_user_templates operation.
//
// Get a list of User Templates with optional pagination.
//
// GET /api/user_template
func (UnimplementedHandler) GetUserTemplates(ctx context.Context, params GetUserTemplatesParams) (r GetUserTemplatesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserUsage implements get_user_usage operation.
//
// Get users usage.
//
// GET /api/user/{username}/usage
func (UnimplementedHandler) GetUserUsage(ctx context.Context, params GetUserUsageParams) (r GetUserUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements get_users operation.
//
// Get all users.
//
// GET /api/users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsersUsage implements get_users_usage operation.
//
// Get all users usage.
//
// GET /api/users/usage
func (UnimplementedHandler) GetUsersUsage(ctx context.Context, params GetUsersUsageParams) (r GetUsersUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModifyAdmin implements modify_admin operation.
//
// Modify an existing admin's details.
//
// PUT /api/admin/{username}
func (UnimplementedHandler) ModifyAdmin(ctx context.Context, req *AdminModify, params ModifyAdminParams) (r ModifyAdminRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModifyCoreConfig implements modify_core_config operation.
//
// Modify the core configuration and restart the core.
//
// PUT /api/core/config
func (UnimplementedHandler) ModifyCoreConfig(ctx context.Context, req *ModifyCoreConfigReq) (r ModifyCoreConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModifyHosts implements modify_hosts operation.
//
// Modify proxy hosts and update the configuration.
//
// PUT /api/hosts
func (UnimplementedHandler) ModifyHosts(ctx context.Context, req ModifyHostsReq) (r ModifyHostsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModifyNode implements modify_node operation.
//
// Update a node's details. Only accessible to sudo admins.
//
// PUT /api/node/{node_id}
func (UnimplementedHandler) ModifyNode(ctx context.Context, req *NodeModify, params ModifyNodeParams) (r ModifyNodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModifyUser implements modify_user operation.
//
// Modify an existing user
// - **username**: Cannot be changed. Used to identify the user.
// - **status**: User's new status. Can be 'active', 'disabled', 'on_hold', 'limited', or 'expired'.
// - **expire**: UTC timestamp for new account expiration. Set to `0` for unlimited, `null` for no
// change.
// - **data_limit**: New max data usage in bytes (e.g., `1073741824` for 1GB). Set to `0` for
// unlimited, `null` for no change.
// - **data_limit_reset_strategy**: New strategy for data limit reset. Options include 'daily',
// 'weekly', 'monthly', or 'no_reset'.
// - **proxies**: Dictionary of new protocol settings (e.g., `vmess`, `vless`). Empty dictionary
// means no change.
// - **inbounds**: Dictionary of new protocol tags to specify inbound connections. Empty dictionary
// means no change.
// - **note**: New optional text for additional user information or notes. `null` means no change.
// - **on_hold_timeout**: New UTC timestamp for when `on_hold` status should start or end. Only
// applicable if status is changed to 'on_hold'.
// - **on_hold_expire_duration**: New duration (in seconds) for how long the user should stay in
// `on_hold` status. Only applicable if status is changed to 'on_hold'.
// - **next_plan**: Next user plan (resets after use).
// Note: Fields set to `null` or omitted will not be modified.
//
// PUT /api/user/{username}
func (UnimplementedHandler) ModifyUser(ctx context.Context, req *UserModify, params ModifyUserParams) (r ModifyUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModifyUserTemplate implements modify_user_template operation.
//
// Modify User Template
// - **name** can be up to 64 characters
// - **data_limit** must be in bytes and larger or equal to 0
// - **expire_duration** must be in seconds and larger or equat to 0
// - **inbounds** dictionary of protocol:inbound_tags, empty means all inbounds.
//
// PUT /api/user_template/{template_id}
func (UnimplementedHandler) ModifyUserTemplate(ctx context.Context, req *UserTemplateModify, params ModifyUserTemplateParams) (r ModifyUserTemplateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReconnectNode implements reconnect_node operation.
//
// Trigger a reconnection for the specified node. Only accessible to sudo admins.
//
// POST /api/node/{node_id}/reconnect
func (UnimplementedHandler) ReconnectNode(ctx context.Context, params ReconnectNodeParams) (r ReconnectNodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveAdmin implements remove_admin operation.
//
// Remove an admin from the database.
//
// DELETE /api/admin/{username}
func (UnimplementedHandler) RemoveAdmin(ctx context.Context, params RemoveAdminParams) (r RemoveAdminRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveNode implements remove_node operation.
//
// Delete a node and remove it from xray in the background.
//
// DELETE /api/node/{node_id}
func (UnimplementedHandler) RemoveNode(ctx context.Context, params RemoveNodeParams) (r RemoveNodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveUser implements remove_user operation.
//
// Remove a user.
//
// DELETE /api/user/{username}
func (UnimplementedHandler) RemoveUser(ctx context.Context, params RemoveUserParams) (r RemoveUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveUserTemplate implements remove_user_template operation.
//
// Remove a User Template by its ID.
//
// DELETE /api/user_template/{template_id}
func (UnimplementedHandler) RemoveUserTemplate(ctx context.Context, params RemoveUserTemplateParams) (r RemoveUserTemplateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetAdminUsage implements reset_admin_usage operation.
//
// Resets usage of admin.
//
// POST /api/admin/usage/reset/{username}
func (UnimplementedHandler) ResetAdminUsage(ctx context.Context, params ResetAdminUsageParams) (r ResetAdminUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetUserDataUsage implements reset_user_data_usage operation.
//
// Reset user data usage.
//
// POST /api/user/{username}/reset
func (UnimplementedHandler) ResetUserDataUsage(ctx context.Context, params ResetUserDataUsageParams) (r ResetUserDataUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetUsersDataUsage implements reset_users_data_usage operation.
//
// Reset all users data usage.
//
// POST /api/users/reset
func (UnimplementedHandler) ResetUsersDataUsage(ctx context.Context) (r ResetUsersDataUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestartCore implements restart_core operation.
//
// Restart the core and all connected nodes.
//
// POST /api/core/restart
func (UnimplementedHandler) RestartCore(ctx context.Context) (r RestartCoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeUserSubscription implements revoke_user_subscription operation.
//
// Revoke users subscription (Subscription link and proxies).
//
// POST /api/user/{username}/revoke_sub
func (UnimplementedHandler) RevokeUserSubscription(ctx context.Context, params RevokeUserSubscriptionParams) (r RevokeUserSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetOwner implements set_owner operation.
//
// Set a new owner (admin) for a user.
//
// PUT /api/user/{username}/set-owner
func (UnimplementedHandler) SetOwner(ctx context.Context, params SetOwnerParams) (r SetOwnerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UserGetUsage implements user_get_usage operation.
//
// Fetches the usage statistics for the user within a specified date range.
//
// GET /sub/{token}/usage
func (UnimplementedHandler) UserGetUsage(ctx context.Context, params UserGetUsageParams) (r UserGetUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UserSubscription implements user_subscription operation.
//
// Provides a subscription link based on the user agent (Clash, V2Ray, etc.).
//
// GET /sub/{token}/
func (UnimplementedHandler) UserSubscription(ctx context.Context, params UserSubscriptionParams) (r UserSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UserSubscriptionInfo implements user_subscription_info operation.
//
// Retrieves detailed information about the user's subscription.
//
// GET /sub/{token}/info
func (UnimplementedHandler) UserSubscriptionInfo(ctx context.Context, params UserSubscriptionInfoParams) (r UserSubscriptionInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UserSubscriptionWithClientType implements user_subscription_with_client_type operation.
//
// Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).
//
// GET /sub/{token}/{client_type}
func (UnimplementedHandler) UserSubscriptionWithClientType(ctx context.Context, params UserSubscriptionWithClientTypeParams) (r UserSubscriptionWithClientTypeRes, _ error) {
	return r, ht.ErrNotImplemented
}
