// Code generated by ogen, DO NOT EDIT.

package marzban

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch r.Method {
				case "GET":
					s.handleBaseRequest([0]string{}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, "GET")
				}

				return
			}
			switch elem[0] {
			case 'a': // Prefix: "api/"

				if l := len("api/"); len(elem) >= l && elem[0:l] == "api/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "admin"

					if l := len("admin"); len(elem) >= l && elem[0:l] == "admin" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetCurrentAdminRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateAdminRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET,POST")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 't': // Prefix: "token"
							origElem := elem
							if l := len("token"); len(elem) >= l && elem[0:l] == "token" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAdminTokenRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

							elem = origElem
						case 'u': // Prefix: "usage/"
							origElem := elem
							if l := len("usage/"); len(elem) >= l && elem[0:l] == "usage/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'r': // Prefix: "reset/"
								origElem := elem
								if l := len("reset/"); len(elem) >= l && elem[0:l] == "reset/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "username"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleResetAdminUsageRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							}
							// Param: "username"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetAdminUsageRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						}
						// Param: "username"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleRemoveAdminRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleModifyAdminRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "DELETE,PUT")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/users/"

							if l := len("/users/"); len(elem) >= l && elem[0:l] == "/users/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "activate"

								if l := len("activate"); len(elem) >= l && elem[0:l] == "activate" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActivateAllDisabledUsersRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'd': // Prefix: "disable"

								if l := len("disable"); len(elem) >= l && elem[0:l] == "disable" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleDisableAllActiveUsersRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetAdminsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				case 'c': // Prefix: "core"

					if l := len("core"); len(elem) >= l && elem[0:l] == "core" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetCoreStatsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "config"

							if l := len("config"); len(elem) >= l && elem[0:l] == "config" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetCoreConfigRequest([0]string{}, elemIsEscaped, w, r)
								case "PUT":
									s.handleModifyCoreConfigRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,PUT")
								}

								return
							}

						case 'r': // Prefix: "restart"

							if l := len("restart"); len(elem) >= l && elem[0:l] == "restart" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleRestartCoreRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						}

					}

				case 'h': // Prefix: "hosts"

					if l := len("hosts"); len(elem) >= l && elem[0:l] == "hosts" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetHostsRequest([0]string{}, elemIsEscaped, w, r)
						case "PUT":
							s.handleModifyHostsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET,PUT")
						}

						return
					}

				case 'i': // Prefix: "inbounds"

					if l := len("inbounds"); len(elem) >= l && elem[0:l] == "inbounds" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetInboundsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				case 'n': // Prefix: "node"

					if l := len("node"); len(elem) >= l && elem[0:l] == "node" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "POST":
							s.handleAddNodeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 's': // Prefix: "settings"
							origElem := elem
							if l := len("settings"); len(elem) >= l && elem[0:l] == "settings" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetNodeSettingsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						}
						// Param: "node_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleRemoveNodeRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetNodeRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleModifyNodeRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "DELETE,GET,PUT")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/reconnect"

							if l := len("/reconnect"); len(elem) >= l && elem[0:l] == "/reconnect" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleReconnectNodeRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetNodesRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/usage"

							if l := len("/usage"); len(elem) >= l && elem[0:l] == "/usage" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetUsageRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					}

				case 's': // Prefix: "system"

					if l := len("system"); len(elem) >= l && elem[0:l] == "system" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetSystemStatsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				case 'u': // Prefix: "user"

					if l := len("user"); len(elem) >= l && elem[0:l] == "user" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "POST":
							s.handleAddUserRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "username"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleRemoveUserRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetUserRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleModifyUserRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "DELETE,GET,PUT")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "active-next"

								if l := len("active-next"); len(elem) >= l && elem[0:l] == "active-next" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActiveNextPlanRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'r': // Prefix: "re"

								if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 's': // Prefix: "set"

									if l := len("set"); len(elem) >= l && elem[0:l] == "set" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleResetUserDataUsageRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

								case 'v': // Prefix: "voke_sub"

									if l := len("voke_sub"); len(elem) >= l && elem[0:l] == "voke_sub" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleRevokeUserSubscriptionRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

								}

							case 's': // Prefix: "set-owner"

								if l := len("set-owner"); len(elem) >= l && elem[0:l] == "set-owner" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "PUT":
										s.handleSetOwnerRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "PUT")
									}

									return
								}

							case 'u': // Prefix: "usage"

								if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetUserUsageRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "GET")
									}

									return
								}

							}

						}

					case '_': // Prefix: "_template"

						if l := len("_template"); len(elem) >= l && elem[0:l] == "_template" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetUserTemplatesRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleAddUserTemplateRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "template_id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleRemoveUserTemplateRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetUserTemplateEndpointRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleModifyUserTemplateRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,PUT")
								}

								return
							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetUsersRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'e': // Prefix: "expired"

								if l := len("expired"); len(elem) >= l && elem[0:l] == "expired" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleDeleteExpiredUsersRequest([0]string{}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetExpiredUsersRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET")
									}

									return
								}

							case 'r': // Prefix: "reset"

								if l := len("reset"); len(elem) >= l && elem[0:l] == "reset" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleResetUsersDataUsageRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'u': // Prefix: "usage"

								if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetUsersUsageRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "GET")
									}

									return
								}

							}

						}

					}

				}

			case 's': // Prefix: "sub/"

				if l := len("sub/"); len(elem) >= l && elem[0:l] == "sub/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "token"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleUserSubscriptionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					switch elem[0] {
					case 'i': // Prefix: "info"
						origElem := elem
						if l := len("info"); len(elem) >= l && elem[0:l] == "info" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleUserSubscriptionInfoRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					case 'u': // Prefix: "usage"
						origElem := elem
						if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleUserGetUsageRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					}
					// Param: "client_type"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleUserSubscriptionWithClientTypeRequest([2]string{
								args[0],
								args[1],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch method {
				case "GET":
					r.name = BaseOperation
					r.summary = "Base"
					r.operationID = "base"
					r.pathPattern = "/"
					r.args = args
					r.count = 0
					return r, true
				default:
					return
				}
			}
			switch elem[0] {
			case 'a': // Prefix: "api/"

				if l := len("api/"); len(elem) >= l && elem[0:l] == "api/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "admin"

					if l := len("admin"); len(elem) >= l && elem[0:l] == "admin" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetCurrentAdminOperation
							r.summary = "Get Current Admin"
							r.operationID = "get_current_admin"
							r.pathPattern = "/api/admin"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateAdminOperation
							r.summary = "Create Admin"
							r.operationID = "create_admin"
							r.pathPattern = "/api/admin"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 't': // Prefix: "token"
							origElem := elem
							if l := len("token"); len(elem) >= l && elem[0:l] == "token" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = AdminTokenOperation
									r.summary = "Admin Token"
									r.operationID = "admin_token"
									r.pathPattern = "/api/admin/token"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'u': // Prefix: "usage/"
							origElem := elem
							if l := len("usage/"); len(elem) >= l && elem[0:l] == "usage/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'r': // Prefix: "reset/"
								origElem := elem
								if l := len("reset/"); len(elem) >= l && elem[0:l] == "reset/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "username"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ResetAdminUsageOperation
										r.summary = "Reset Admin Usage"
										r.operationID = "reset_admin_usage"
										r.pathPattern = "/api/admin/usage/reset/{username}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}
							// Param: "username"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetAdminUsageOperation
									r.summary = "Get Admin Usage"
									r.operationID = "get_admin_usage"
									r.pathPattern = "/api/admin/usage/{username}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}
						// Param: "username"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = RemoveAdminOperation
								r.summary = "Remove Admin"
								r.operationID = "remove_admin"
								r.pathPattern = "/api/admin/{username}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = ModifyAdminOperation
								r.summary = "Modify Admin"
								r.operationID = "modify_admin"
								r.pathPattern = "/api/admin/{username}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/users/"

							if l := len("/users/"); len(elem) >= l && elem[0:l] == "/users/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "activate"

								if l := len("activate"); len(elem) >= l && elem[0:l] == "activate" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ActivateAllDisabledUsersOperation
										r.summary = "Activate All Disabled Users"
										r.operationID = "activate_all_disabled_users"
										r.pathPattern = "/api/admin/{username}/users/activate"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'd': // Prefix: "disable"

								if l := len("disable"); len(elem) >= l && elem[0:l] == "disable" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = DisableAllActiveUsersOperation
										r.summary = "Disable All Active Users"
										r.operationID = "disable_all_active_users"
										r.pathPattern = "/api/admin/{username}/users/disable"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetAdminsOperation
								r.summary = "Get Admins"
								r.operationID = "get_admins"
								r.pathPattern = "/api/admins"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'c': // Prefix: "core"

					if l := len("core"); len(elem) >= l && elem[0:l] == "core" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetCoreStatsOperation
							r.summary = "Get Core Stats"
							r.operationID = "get_core_stats"
							r.pathPattern = "/api/core"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "config"

							if l := len("config"); len(elem) >= l && elem[0:l] == "config" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetCoreConfigOperation
									r.summary = "Get Core Config"
									r.operationID = "get_core_config"
									r.pathPattern = "/api/core/config"
									r.args = args
									r.count = 0
									return r, true
								case "PUT":
									r.name = ModifyCoreConfigOperation
									r.summary = "Modify Core Config"
									r.operationID = "modify_core_config"
									r.pathPattern = "/api/core/config"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'r': // Prefix: "restart"

							if l := len("restart"); len(elem) >= l && elem[0:l] == "restart" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = RestartCoreOperation
									r.summary = "Restart Core"
									r.operationID = "restart_core"
									r.pathPattern = "/api/core/restart"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'h': // Prefix: "hosts"

					if l := len("hosts"); len(elem) >= l && elem[0:l] == "hosts" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetHostsOperation
							r.summary = "Get Hosts"
							r.operationID = "get_hosts"
							r.pathPattern = "/api/hosts"
							r.args = args
							r.count = 0
							return r, true
						case "PUT":
							r.name = ModifyHostsOperation
							r.summary = "Modify Hosts"
							r.operationID = "modify_hosts"
							r.pathPattern = "/api/hosts"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'i': // Prefix: "inbounds"

					if l := len("inbounds"); len(elem) >= l && elem[0:l] == "inbounds" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetInboundsOperation
							r.summary = "Get Inbounds"
							r.operationID = "get_inbounds"
							r.pathPattern = "/api/inbounds"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'n': // Prefix: "node"

					if l := len("node"); len(elem) >= l && elem[0:l] == "node" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							r.name = AddNodeOperation
							r.summary = "Add Node"
							r.operationID = "add_node"
							r.pathPattern = "/api/node"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 's': // Prefix: "settings"
							origElem := elem
							if l := len("settings"); len(elem) >= l && elem[0:l] == "settings" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetNodeSettingsOperation
									r.summary = "Get Node Settings"
									r.operationID = "get_node_settings"
									r.pathPattern = "/api/node/settings"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}
						// Param: "node_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = RemoveNodeOperation
								r.summary = "Remove Node"
								r.operationID = "remove_node"
								r.pathPattern = "/api/node/{node_id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetNodeOperation
								r.summary = "Get Node"
								r.operationID = "get_node"
								r.pathPattern = "/api/node/{node_id}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = ModifyNodeOperation
								r.summary = "Modify Node"
								r.operationID = "modify_node"
								r.pathPattern = "/api/node/{node_id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/reconnect"

							if l := len("/reconnect"); len(elem) >= l && elem[0:l] == "/reconnect" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ReconnectNodeOperation
									r.summary = "Reconnect Node"
									r.operationID = "reconnect_node"
									r.pathPattern = "/api/node/{node_id}/reconnect"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetNodesOperation
								r.summary = "Get Nodes"
								r.operationID = "get_nodes"
								r.pathPattern = "/api/nodes"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/usage"

							if l := len("/usage"); len(elem) >= l && elem[0:l] == "/usage" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetUsageOperation
									r.summary = "Get Usage"
									r.operationID = "get_usage"
									r.pathPattern = "/api/nodes/usage"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				case 's': // Prefix: "system"

					if l := len("system"); len(elem) >= l && elem[0:l] == "system" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetSystemStatsOperation
							r.summary = "Get System Stats"
							r.operationID = "get_system_stats"
							r.pathPattern = "/api/system"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'u': // Prefix: "user"

					if l := len("user"); len(elem) >= l && elem[0:l] == "user" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							r.name = AddUserOperation
							r.summary = "Add User"
							r.operationID = "add_user"
							r.pathPattern = "/api/user"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "username"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = RemoveUserOperation
								r.summary = "Remove User"
								r.operationID = "remove_user"
								r.pathPattern = "/api/user/{username}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetUserOperation
								r.summary = "Get User"
								r.operationID = "get_user"
								r.pathPattern = "/api/user/{username}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = ModifyUserOperation
								r.summary = "Modify User"
								r.operationID = "modify_user"
								r.pathPattern = "/api/user/{username}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "active-next"

								if l := len("active-next"); len(elem) >= l && elem[0:l] == "active-next" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ActiveNextPlanOperation
										r.summary = "Active Next Plan"
										r.operationID = "active_next_plan"
										r.pathPattern = "/api/user/{username}/active-next"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'r': // Prefix: "re"

								if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 's': // Prefix: "set"

									if l := len("set"); len(elem) >= l && elem[0:l] == "set" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = ResetUserDataUsageOperation
											r.summary = "Reset User Data Usage"
											r.operationID = "reset_user_data_usage"
											r.pathPattern = "/api/user/{username}/reset"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								case 'v': // Prefix: "voke_sub"

									if l := len("voke_sub"); len(elem) >= l && elem[0:l] == "voke_sub" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = RevokeUserSubscriptionOperation
											r.summary = "Revoke User Subscription"
											r.operationID = "revoke_user_subscription"
											r.pathPattern = "/api/user/{username}/revoke_sub"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							case 's': // Prefix: "set-owner"

								if l := len("set-owner"); len(elem) >= l && elem[0:l] == "set-owner" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "PUT":
										r.name = SetOwnerOperation
										r.summary = "Set Owner"
										r.operationID = "set_owner"
										r.pathPattern = "/api/user/{username}/set-owner"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'u': // Prefix: "usage"

								if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetUserUsageOperation
										r.summary = "Get User Usage"
										r.operationID = "get_user_usage"
										r.pathPattern = "/api/user/{username}/usage"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case '_': // Prefix: "_template"

						if l := len("_template"); len(elem) >= l && elem[0:l] == "_template" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetUserTemplatesOperation
								r.summary = "Get User Templates"
								r.operationID = "get_user_templates"
								r.pathPattern = "/api/user_template"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = AddUserTemplateOperation
								r.summary = "Add User Template"
								r.operationID = "add_user_template"
								r.pathPattern = "/api/user_template"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "template_id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = RemoveUserTemplateOperation
									r.summary = "Remove User Template"
									r.operationID = "remove_user_template"
									r.pathPattern = "/api/user_template/{template_id}"
									r.args = args
									r.count = 1
									return r, true
								case "GET":
									r.name = GetUserTemplateEndpointOperation
									r.summary = "Get User Template Endpoint"
									r.operationID = "get_user_template_endpoint"
									r.pathPattern = "/api/user_template/{template_id}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = ModifyUserTemplateOperation
									r.summary = "Modify User Template"
									r.operationID = "modify_user_template"
									r.pathPattern = "/api/user_template/{template_id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetUsersOperation
								r.summary = "Get Users"
								r.operationID = "get_users"
								r.pathPattern = "/api/users"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'e': // Prefix: "expired"

								if l := len("expired"); len(elem) >= l && elem[0:l] == "expired" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = DeleteExpiredUsersOperation
										r.summary = "Delete Expired Users"
										r.operationID = "delete_expired_users"
										r.pathPattern = "/api/users/expired"
										r.args = args
										r.count = 0
										return r, true
									case "GET":
										r.name = GetExpiredUsersOperation
										r.summary = "Get Expired Users"
										r.operationID = "get_expired_users"
										r.pathPattern = "/api/users/expired"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'r': // Prefix: "reset"

								if l := len("reset"); len(elem) >= l && elem[0:l] == "reset" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ResetUsersDataUsageOperation
										r.summary = "Reset Users Data Usage"
										r.operationID = "reset_users_data_usage"
										r.pathPattern = "/api/users/reset"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'u': // Prefix: "usage"

								if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetUsersUsageOperation
										r.summary = "Get Users Usage"
										r.operationID = "get_users_usage"
										r.pathPattern = "/api/users/usage"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			case 's': // Prefix: "sub/"

				if l := len("sub/"); len(elem) >= l && elem[0:l] == "sub/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "token"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = UserSubscriptionOperation
							r.summary = "User Subscription"
							r.operationID = "user_subscription"
							r.pathPattern = "/sub/{token}/"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case 'i': // Prefix: "info"
						origElem := elem
						if l := len("info"); len(elem) >= l && elem[0:l] == "info" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = UserSubscriptionInfoOperation
								r.summary = "User Subscription Info"
								r.operationID = "user_subscription_info"
								r.pathPattern = "/sub/{token}/info"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

						elem = origElem
					case 'u': // Prefix: "usage"
						origElem := elem
						if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = UserGetUsageOperation
								r.summary = "User Get Usage"
								r.operationID = "user_get_usage"
								r.pathPattern = "/sub/{token}/usage"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}
					// Param: "client_type"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = UserSubscriptionWithClientTypeOperation
							r.summary = "User Subscription With Client Type"
							r.operationID = "user_subscription_with_client_type"
							r.pathPattern = "/sub/{token}/{client_type}"
							r.args = args
							r.count = 2
							return r, true
						default:
							return
						}
					}

				}

			}

		}
	}
	return r, false
}
